### ISSUE TITLE
Version Matching

### ISSUE THREAD

**Issue by mdmdmdmd** [danielmewes/php-rql#114] opened 2015-12-03 11:54 UTC
Daniel:

How much API difference is there between 2.1 and 2.2 support in php-rql?

What is your plan to keep the PHP library up to date with the changing core Rethink API?

There are some tasks, like contributing to keeping the version up to date, which I need to plan time for if there will be a significant delay in version matching.

**Comment by mbrevda** [comment] 2015-12-03 12:42
While I'm not the maintainer of this repo, personally I'm waiting for #107 to merge before looking at other things. While I don't think there is much of a difference between 2.1 and 2.2 (`values()` comes to mind), PR are always appreciated.

**Comment by danielmewes** [comment] 2015-12-03 23:18
@mdmdmdmd The differences are pretty small, and the 2.1 PHP-RQL version is 100% compatible with RethinkDB 2.2 except for the missing new features.

Apart from the `values()` term that @mbrevda mentioned, the other two missing things are support for the optional argument to `r\uuid()` and the new `$connection->server()` function to get the ID and name of the server one is currently connected to.

It usually takes me a few weeks after the new server release to update PHP-RQL.
In general it should only matter if you need to use the new API features in a new server version.

**Comment by danielmewes** [comment] 2015-12-03 23:18
(closing since it's not a bug)

**Closed by danielmewes** 2015-12-03 23:18 UTC
